### ISSUE TITLE
Uncaught negative w/h scissoring when window size is too small

### ISSUE THREAD

**Issue by Gennadiyev** [snowkittykira/love-error-explorer#1]
Hi! I've been extensively using this project for my primary debugging tool recently, and I accidentally found this issue when coding a level editor where the window is resizable.

When you made the window too small for some `section`'s to work, this error will *always* occur.

Sample:

```
Error

my_project_name.lua:152: bad argument #1 to 'ipairs' (table expected, got nil)

error during error handling: libs/error_explorer.lua:486: Can't set scissor with negative width and/or height.


Traceback

[love "callbacks.lua"]:239: in function 'errhand'
libs/error_explorer.lua:704: in function <libs/error_explorer.lua:697>
[C]: in function 'xpcall'
```

A possible fix could be a simple clamp, which is exactly what I changed on my local machine:

```lua
local function section (new_sx, new_sy, new_sw, new_sh)
  -- avoid negative sizes
  new_sw = math.max (new_sw, 0)
  new_sh = math.max (new_sh, 0)
  sx, sy = new_sx, new_sy
  sw, sh = new_sw, new_sh
  x, y = sx, sy
  over_section =
    mx >= sx and mx < sx + sw and
    my >= sy and my < sy + sh
  love.graphics.setScissor (sx, sy, sw, sh)
end
```

But directly applying this fix might cause unexpected, confusing display results for the end users that are not aware.

Another option could be showing a `WINDOW TOO SMALL` exception as a placeholder text, or to raise the error directly to Lua with a more sensible error message (e.g. `error_handler cannot work for small windows`).

Thanks for your work! I really liked the grays used in the project!

**Comment by snowkittykira** [comment]
sorry for missing this! thanks for the report, i found it as well and just pushed a fix.
